spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/junjieliao593/myconfig/
#          search-paths: repo
#          username:
#          password:

server:
  port: 1201